"""
Backend-driven CRUD views demonstrating automatic Fixi.js integration.

Shows how to use FxTableMixin for zero-template-code inline editing.
"""

from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, UpdateView, DeleteView

from dj_fixi.mixins import FxTableMixin, FxResponseMixin
from dj_fixi.forms import InlineEditForm

from .models import Product
from .forms import ProductForm


class ProductListBackendDriven(FxTableMixin, ListView):
    """
    ListView with automatic table generation and inline editing.

    Template only needs: {{ table }}
    All Fixi attributes are auto-generated by the backend.
    """

    model = Product
    template_name = "products/list_backend_driven.html"
    context_object_name = "products"

    # Configure table rendering
    table_fields = ["name", "price", "stock", "is_active"]
    editable_fields = ["name", "stock"]  # Double-click to edit
    table_actions = ["edit", "delete"]
    table_formatters = {
        "price": lambda p: f"${p:.2f}",
        "is_active": lambda v: "✓" if v else "✗",
    }


class ProductRowView(FxResponseMixin, UpdateView):
    """
    Returns a single table row or inline edit form.

    GET: Returns read-only row HTML
    POST: Returns updated row after save
    """

    model = Product
    form_class = ProductForm
    template_name = "products/row.html"

    def get(self, request, *args, **kwargs):
        """Return read-only row HTML."""
        obj = self.get_object()

        # Return editable form if ?edit=1
        if request.GET.get("edit") == "1":
            form = self.form_class(instance=obj)
            inline_form = InlineEditForm(
                form=form,
                action=reverse_lazy("product_update_row", args=[obj.pk]),
                row_id=f"row-{obj.pk}",
            )
            return HttpResponse(inline_form.render())

        # Return read-only row
        return self.render_to_response(self.get_context_data(object=obj))

    def post(self, request, *args, **kwargs):
        """Handle inline edit form submission."""
        self.object = self.get_object()
        form = self.form_class(request.POST, instance=self.object)

        if form.is_valid():
            form.save()
            # Return updated read-only row
            return self.render_to_response(self.get_context_data(object=self.object))

        # Return form with errors
        inline_form = InlineEditForm(
            form=form,
            action=reverse_lazy("product_update_row", args=[self.object.pk]),
            row_id=f"row-{self.object.pk}",
        )
        return HttpResponse(inline_form.render(), status=422)


class ProductDeleteBackendDriven(FxResponseMixin, DeleteView):
    """Delete product and return empty response for row removal."""

    model = Product
    success_url = reverse_lazy("product_list_backend")

    def delete(self, request, *args, **kwargs):
        """Delete and return empty response."""
        self.object = self.get_object()
        self.object.delete()
        # Return empty response - Fixi will swap outerHTML with nothing
        return HttpResponse("", status=200)
